import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from  "./provider";
import Header from "@/app/_layouts/header";
import Footer from "@/app/_layouts/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <Provider>
            <body className="h-lvh flex flex-col justify-between align-middle">
                 <div className="h-lvh flex flex-col items-center">
                    <Header/>
                    <main className="max-w-content w-full p-sm">
                            {children}
                    </main>
                 </div>
                <Footer/>
            </body>
        </Provider>
    </html>
  );
}
